import { useEffect, useState } from 'react';
import { Alert, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { currentProfile, reviewSales } from '@/lib/api';
import { supabase } from '@/lib/supabase';

export default function Admin(){const router=useRouter();const [p,setP]=useState<any>(null);const [rows,setRows]=useState<any[]>([]);const [refreshing,setRefreshing]=useState(false);const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 async function load(){const profile=await currentProfile();setP(profile);const {data,error}=await supabase.from('daily_operations').select('*').eq('work_date',date).order('full_name');if(error)throw error;setRows(data||[])}useEffect(()=>{load().catch(()=>{})},[]);
 async function approve(employeeId:string,act:'approve'|'reject'){const {data}=await supabase.from('sales_entries').select('id').eq('employee_id',employeeId).eq('business_date',date).maybeSingle();if(!data?.id)return Alert.alert('لا توجد مبيعات','لا يوجد سجل مبيعات لهذا الموظف اليوم');try{await reviewSales(data.id,act,act==='reject'?'يرجى مراجعة المبيعات وإعادة الإرسال':undefined);await load()}catch(e:any){Alert.alert('خطأ',e.message)}}
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.wrap} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false)}}>}><View style={s.head}><View><Text style={s.hello}>الإدارة</Text><Text style={s.name}>{p?.full_name||'سلطان عبد السلام هوسه'}</Text></View><TouchableOpacity onPress={async()=>{await supabase.auth.signOut();router.replace('/')}}><Text style={s.logout}>خروج</Text></TouchableOpacity></View><View style={s.summary}><Mini t="الموظفين" v={rows.length}/><Mini t="مفتوح" v={rows.filter(x=>x.shift_status==='open').length}/><Mini t="منتهي" v={rows.filter(x=>x.shift_status==='ended').length}/><Mini t="غياب" v={rows.filter(x=>x.shift_status==='absent').length}/></View><Text style={s.section}>جدول اليوم • {date}</Text>{rows.map(r=><View key={r.employee_id} style={s.card}><View style={s.row}><Text style={s.emp}>{r.full_name}</Text><Text style={s.state}>{r.shift_status==='open'?'الشفت مفتوح':r.shift_status==='ended'?'تم إنهاء الشفت':r.shift_status==='absent'?'غائب':'—'}</Text></View><Text style={s.meta}>📍 {r.assigned_location||'غير موزع'} • المبيعات {r.total_units||0} • النقاط {r.total_points||0}</Text><Text style={s.meta}>35:{r.package_35||0}  |  58:{r.package_58||0}  |  75:{r.package_75||0}  |  104:{r.package_104||0}</Text>{r.sales_status==='submitted'&&<View style={s.actions}><TouchableOpacity style={s.ok} onPress={()=>approve(r.employee_id,'approve')}><Text style={s.bt}>اعتماد</Text></TouchableOpacity><TouchableOpacity style={s.no} onPress={()=>approve(r.employee_id,'reject')}><Text style={s.bt}>رفض</Text></TouchableOpacity></View>}</View>)}</ScrollView></SafeAreaView>}
function Mini({t,v}:{t:string,v:any}){return <View style={s.mini}><Text style={s.mv}>{v}</Text><Text style={s.mt}>{t}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F4F7FB'},wrap:{padding:18,paddingBottom:50},head:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center',marginBottom:16},hello:{textAlign:'right',color:'#8A95A3'},name:{textAlign:'right',fontWeight:'900',fontSize:21,color:'#17233C'},logout:{color:'#A33',fontWeight:'800'},summary:{flexDirection:'row-reverse',gap:7,marginBottom:20},mini:{flex:1,backgroundColor:'#17233C',borderRadius:15,padding:10,alignItems:'center'},mv:{fontSize:20,fontWeight:'900',color:'#fff'},mt:{fontSize:10,color:'#C7CFDA'},section:{textAlign:'right',fontSize:19,fontWeight:'900',marginBottom:10,color:'#17233C'},card:{backgroundColor:'#fff',borderRadius:18,padding:15,marginBottom:10},row:{flexDirection:'row-reverse',justifyContent:'space-between',gap:10},emp:{fontWeight:'900',fontSize:16,color:'#17233C',flex:1,textAlign:'right'},state:{color:'#657180',fontSize:12},meta:{textAlign:'right',color:'#778291',fontSize:12,marginTop:7},actions:{flexDirection:'row-reverse',gap:8,marginTop:12},ok:{flex:1,backgroundColor:'#159A74',padding:11,borderRadius:12},no:{flex:1,backgroundColor:'#B42318',padding:11,borderRadius:12},bt:{textAlign:'center',color:'#fff',fontWeight:'900'}});
