import { useCallback, useState } from 'react';
import { Alert, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { currentProfile, endShift, selfAbsent, startShift } from '@/lib/api';
import { supabase } from '@/lib/supabase';
import { Button, Metric, Pill, ScreenTitle, Section } from '@/lib/ui';
import { C, R } from '@/lib/theme';

const businessDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()-2*60*60*1000));
const time=(v?:string|null)=>v?new Date(v).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Riyadh'}):'—';
export default function Home(){
 const router=useRouter(); const [profile,setProfile]=useState<any>();const [today,setToday]=useState<any>();const [month,setMonth]=useState<any>();const [busy,setBusy]=useState(false);const [refreshing,setRefreshing]=useState(false);
 async function load(){const p=await currentProfile();setProfile(p);const d=businessDate();const [op,mp]=await Promise.all([supabase.from('daily_operations').select('*').eq('employee_id',p.id).eq('work_date',d).maybeSingle(),supabase.from('monthly_performance').select('*').eq('employee_id',p.id).eq('year',+d.slice(0,4)).eq('month',+d.slice(5,7)).maybeSingle()]);setToday(op.data);setMonth(mp.data)}
 useFocusEffect(useCallback(()=>{load().catch(()=>{})},[]));
 async function run(fn:()=>Promise<any>,ok:string){setBusy(true);try{await fn();await load();Alert.alert('تم',ok)}catch(e:any){Alert.alert('تعذر التنفيذ',e.message||'حدث خطأ')}finally{setBusy(false)}}
 const shift=today?.shift_status;const absent=shift==='absent'||today?.attendance_status==='absent';const total=Number(month?.total_points||0),target=Number(month?.eligible_target_points||0),pct=target?Math.round(total/target*1000)/10:0;const daily=absent?0:Number(today?.eligible_target_points||today?.daily_target_points||0);const assigned=today?.assigned_location_id;
 const tone=shift==='open'?'success':shift==='ended'?'info':absent?'danger':'neutral';const shiftText=shift==='open'?'الشفت مفتوح':shift==='ended'?'تم إنهاء الشفت':absent?'غائب':'لم يبدأ';
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false)}}/>}>
  <ScreenTitle eyebrow="الموظف" title={profile?.full_name||'مبيعات الجنوبية'} right={<TouchableOpacity onPress={()=>router.push('/notifications')} style={s.bell}><Text style={s.bellText}>●</Text></TouchableOpacity>}/>
  <View style={s.hero}><View style={s.heroTop}><View><Text style={s.heroLabel}>إنجاز الشهر</Text><Text style={s.heroValue}>{Math.round(total).toLocaleString('ar-SA')}</Text><Text style={s.heroUnit}>نقطة محققة</Text></View><View style={s.percentCircle}><Text style={s.percent}>{pct}%</Text><Text style={s.percentSub}>نسبة الإنجاز</Text></View></View><View style={s.track}><View style={[s.fill,{width:`${Math.min(100,pct)}%`}]} /></View><View style={s.heroBottom}><Text style={s.heroMeta}>المطلوب حسب أيام دوامك: {Math.round(target).toLocaleString('ar-SA')}</Text><Text style={s.heroMeta}>تارجت الشهر: 3,300</Text></View></View>
  <Section title="وضع اليوم" right={<Pill text={shiftText} tone={tone as any}/>}> <View style={s.statusCard}><View style={s.statusLine}><Text style={s.statusKey}>الموقع</Text><Text style={s.statusValue}>{today?.assigned_location||'لم يتم توزيع موقع'}</Text></View><View style={s.div}/><View style={s.statusGrid}><Info label="بداية" value={time(today?.started_at)}/><Info label="نهاية" value={time(today?.ended_at)}/><Info label="تارجت اليوم" value={absent?'0 (غياب)':String(Math.round(daily))}/></View>{absent&&<View style={s.absentNote}><Text style={s.absentText}>هذا اليوم لا يُضاف إلى التارجت المطلوب لأن حالتك غياب.</Text></View>}</View></Section>
  <Section title="أرقام اليوم"><View style={s.metrics}><Metric label="النقاط" value={Math.round(Number(today?.total_points||0))} style={s.half}/><Metric label="الشرائح" value={today?.total_units||0} style={s.half}/></View><View style={s.packages}>{[['35',5],['58',10],['75',10],['104',12]].map(([code,pts])=><View style={s.pkg} key={String(code)}><Text style={s.pkgCode}>{code}</Text><Text style={s.pkgCount}>{today?.[`package_${code}`]||0}</Text><Text style={s.pkgPts}>{pts} ن/شريحة</Text></View>)}</View></Section>
  <Section title="الإجراء التالي"><View style={s.actionCard}>{!shift&&<><Text style={s.actionHint}>{assigned?'أنت جاهز للتحضير من الموقع الموزع لك.':'بانتظار الإدارة لتوزيع موقع اليوم.'}</Text><Button disabled={busy||!assigned} title="بداية الدوام / تحضير" onPress={()=>run(()=>startShift(assigned),'تم فتح الشفت وتسجيل حضورك')}/><View style={{height:8}}/><Button disabled={busy} variant="secondary" title="رفع غياب اليوم" onPress={()=>Alert.alert('تأكيد الغياب','لن يُطلب منك تارجت لهذا اليوم بعد تسجيل الغياب.',[{text:'إلغاء'},{text:'تسجيل الغياب',style:'destructive',onPress:()=>run(()=>selfAbsent(),'تم تسجيل الغياب وإلغاء تارجت اليوم')}])}/></>}{shift==='open'&&<><Text style={s.actionHint}>الشفت مفتوح. عند انتهاء دوامك يمكنك الإنهاء من أي مكان وسيُحفظ موقع النهاية والمسافة.</Text><Button disabled={busy} title="إنهاء الشفت" onPress={()=>run(()=>endShift(),'تم إنهاء الشفت')}/></>}{shift==='ended'&&<><Text style={s.actionHint}>دوامك انتهى. سجّل المبيعات وأرسلها للاعتماد.</Text><Button title={today?.sales_status==='approved'?'عرض مبيعات اليوم':'تسجيل / متابعة المبيعات'} onPress={()=>router.push('/sales')}/></>}{absent&&<><Text style={s.actionHint}>تم تسجيلك غائبًا اليوم. لا يوجد تارجت مطلوب ولا إجراءات شفت.</Text><Pill text="التارجت اليومي = 0" tone="danger"/></>}</View></Section>
  <View style={s.footerRow}><TouchableOpacity onPress={()=>router.push('/history')}><Text style={s.footerLink}>السجل الشهري</Text></TouchableOpacity><TouchableOpacity onPress={()=>router.push('/notifications')}><Text style={s.footerLink}>الإشعارات</Text></TouchableOpacity><TouchableOpacity onPress={async()=>{await supabase.auth.signOut();router.replace('/')}}><Text style={s.logout}>تسجيل الخروج</Text></TouchableOpacity></View>
 </ScrollView></SafeAreaView>}
function Info({label,value}:{label:string,value:string}){return <View style={{flex:1}}><Text style={s.infoLabel}>{label}</Text><Text style={s.infoValue}>{value}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{padding:18,paddingBottom:60},bell:{width:42,height:42,borderRadius:14,backgroundColor:C.card,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},bellText:{fontSize:16,color:C.primary},hero:{backgroundColor:C.navy,borderRadius:R.xl,padding:20,marginTop:20},heroTop:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},heroLabel:{textAlign:'right',color:'#BFC8D6',fontSize:12},heroValue:{textAlign:'right',color:'#fff',fontSize:38,fontWeight:'900',marginTop:3},heroUnit:{textAlign:'right',color:'#91A0B4',fontSize:11},percentCircle:{width:95,height:95,borderRadius:48,backgroundColor:C.navy2,alignItems:'center',justifyContent:'center'},percent:{fontSize:23,fontWeight:'900',color:'#7EE4BE'},percentSub:{fontSize:9,color:'#B8C3D0',marginTop:2},track:{height:8,borderRadius:9,backgroundColor:'#2A3D58',overflow:'hidden',marginTop:18},fill:{height:'100%',backgroundColor:'#51D0A5'},heroBottom:{flexDirection:'row-reverse',justifyContent:'space-between',marginTop:9,gap:10},heroMeta:{color:'#AEBAC8',fontSize:10},statusCard:{backgroundColor:C.card,borderRadius:R.lg,padding:16,borderWidth:1,borderColor:C.line},statusLine:{flexDirection:'row-reverse',justifyContent:'space-between',gap:15},statusKey:{color:C.muted,fontSize:12,fontWeight:'700'},statusValue:{color:C.ink,fontSize:13,fontWeight:'900',flex:1,textAlign:'right'},div:{height:1,backgroundColor:C.line,marginVertical:14},statusGrid:{flexDirection:'row-reverse',gap:10},infoLabel:{textAlign:'right',fontSize:10,color:C.faint},infoValue:{textAlign:'right',fontSize:14,fontWeight:'900',color:C.ink,marginTop:4},absentNote:{backgroundColor:C.dangerSoft,padding:11,borderRadius:R.sm,marginTop:14},absentText:{textAlign:'right',fontSize:11,fontWeight:'700',color:C.danger,lineHeight:18},metrics:{flexDirection:'row-reverse',gap:10},half:{flex:1},packages:{flexDirection:'row-reverse',gap:8,marginTop:10},pkg:{flex:1,backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:R.md,paddingVertical:12,alignItems:'center'},pkgCode:{fontSize:11,fontWeight:'900',color:C.muted},pkgCount:{fontSize:21,fontWeight:'900',color:C.ink,marginTop:4},pkgPts:{fontSize:8,color:C.faint,marginTop:2},actionCard:{backgroundColor:C.card,borderRadius:R.lg,padding:16,borderWidth:1,borderColor:C.line},actionHint:{textAlign:'right',color:C.muted,lineHeight:20,fontSize:12,marginBottom:13},footerRow:{flexDirection:'row-reverse',justifyContent:'space-between',marginTop:28,paddingHorizontal:4},footerLink:{color:C.primary,fontWeight:'800',fontSize:12},logout:{color:C.danger,fontWeight:'800',fontSize:12}});
