import { useCallback, useState } from 'react';
import { Alert, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { currentProfile, endShift, selfAbsent, startShift } from '@/lib/api';
import { supabase } from '@/lib/supabase';

type Op=any;
export default function Home(){
 const router=useRouter(); const [profile,setProfile]=useState<any>(null);const [today,setToday]=useState<Op>(null);const [month,setMonth]=useState<any>(null);const [busy,setBusy]=useState(false);const [refreshing,setRefreshing]=useState(false);
 const load=async()=>{const p=await currentProfile();setProfile(p);const now=new Date();const d=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);const [op,mp]=await Promise.all([supabase.from('daily_operations').select('*').eq('employee_id',p.id).eq('work_date',d).maybeSingle(),supabase.from('monthly_performance').select('*').eq('employee_id',p.id).eq('year',Number(d.slice(0,4))).eq('month',Number(d.slice(5,7))).maybeSingle()]);setToday(op.data);setMonth(mp.data)};
 useFocusEffect(useCallback(()=>{load().catch(()=>{})},[]));
 async function action(fn:()=>Promise<any>,success:string){setBusy(true);try{await fn();await load();Alert.alert('تم',success)}catch(e:any){Alert.alert('تعذر التنفيذ',e.message||'حدث خطأ')}finally{setBusy(false)}}
 const assigned=today?.assigned_location_id; const shift=today?.shift_status;
 const total=Number(month?.total_points||0),target=Number(month?.eligible_target_points||0);const pct=target?Math.round(total/target*1000)/10:0;
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false)}}>}>
  <View style={s.head}><View><Text style={s.hello}>مرحبًا</Text><Text style={s.name}>{profile?.full_name||'...'}</Text></View><TouchableOpacity onPress={async()=>{await supabase.auth.signOut();router.replace('/')}}><Text style={s.logout}>خروج</Text></TouchableOpacity></View>
  <View style={s.target}><Text style={s.targetLabel}>التارجت الشهري</Text><Text style={s.targetNum}>3,300</Text><Text style={s.targetSub}>المحقق {total} • المطلوب حتى أيام دوامك {target}</Text><View style={s.progress}><View style={[s.progressFill,{width:`${Math.min(100,pct)}%`}]} /></View><Text style={s.percent}>{pct}%</Text></View>
  <Text style={s.section}>اليوم</Text><View style={s.grid}><Stat t="النقاط" v={today?.total_points||0}/><Stat t="الشرائح" v={today?.total_units||0}/><Stat t="الموقع" v={today?.assigned_location||'—'}/><Stat t="الشفت" v={shift==='open'?'مفتوح':shift==='ended'?'منتهي':shift==='absent'?'غائب':'—'}/></View>
  <Text style={s.section}>الباقات</Text><View style={s.grid}><Stat t="35" v={today?.package_35||0}/><Stat t="58" v={today?.package_58||0}/><Stat t="75" v={today?.package_75||0}/><Stat t="104" v={today?.package_104||0}/></View>
  <Text style={s.section}>العمليات</Text>
  {!shift&&<><TouchableOpacity disabled={busy||!assigned} style={[s.primary,(!assigned||busy)&&s.disabled]} onPress={()=>action(()=>startShift(assigned),'تم فتح الشفت')}><Text style={s.primaryText}>{assigned?'بداية الدوام / تحضير':'بانتظار توزيع موقع اليوم'}</Text></TouchableOpacity><TouchableOpacity disabled={busy} style={s.dangerGhost} onPress={()=>Alert.alert('تأكيد الغياب','هل تريد تسجيل غيابك اليوم؟',[{text:'إلغاء'},{text:'تأكيد',style:'destructive',onPress:()=>action(()=>selfAbsent(),'تم تسجيل الغياب')}])}><Text style={s.dangerText}>رفع الغياب</Text></TouchableOpacity></>}
  {shift==='open'&&<TouchableOpacity disabled={busy} style={s.primary} onPress={()=>action(()=>endShift(),'تم إنهاء الشفت')}><Text style={s.primaryText}>إنهاء الشفت</Text></TouchableOpacity>}
  {shift==='ended'&&<TouchableOpacity style={s.primary} onPress={()=>router.push('/sales')}><Text style={s.primaryText}>{today?.sales_status==='approved'?'عرض المبيعات':'تسجيل / متابعة المبيعات'}</Text></TouchableOpacity>}
  <TouchableOpacity style={s.secondary} onPress={()=>router.push('/notifications')}><Text style={s.secondaryText}>الإشعارات</Text></TouchableOpacity>
 </ScrollView></SafeAreaView>
}
function Stat({t,v}:{t:string,v:any}){return <View style={s.stat}><Text style={s.statT}>{t}</Text><Text numberOfLines={2} style={s.statV}>{String(v)}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F4F7FB'},content:{padding:20,paddingBottom:60},head:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center',marginBottom:20},hello:{textAlign:'right',color:'#8893A2'},name:{textAlign:'right',fontSize:21,fontWeight:'900',color:'#17233C',marginTop:3},logout:{fontWeight:'800',color:'#A33'},target:{backgroundColor:'#17233C',borderRadius:27,padding:23,marginBottom:25},targetLabel:{textAlign:'center',color:'#BFC8D5'},targetNum:{textAlign:'center',color:'#fff',fontSize:44,fontWeight:'900',marginTop:3},targetSub:{textAlign:'center',color:'#CFD6DF',fontSize:12,marginTop:7},progress:{height:10,borderRadius:6,backgroundColor:'#34425C',overflow:'hidden',marginTop:16},progressFill:{height:'100%',backgroundColor:'#35C899'},percent:{textAlign:'center',color:'#75E2BF',fontWeight:'900',marginTop:7},section:{textAlign:'right',fontSize:19,fontWeight:'900',color:'#17233C',marginBottom:12,marginTop:4},grid:{flexDirection:'row-reverse',flexWrap:'wrap',gap:10,marginBottom:18},stat:{width:'48%',backgroundColor:'#fff',borderRadius:19,padding:16,minHeight:85},statT:{textAlign:'right',color:'#8792A1',fontSize:13},statV:{textAlign:'right',fontWeight:'900',fontSize:20,color:'#17233C',marginTop:8},primary:{backgroundColor:'#159A74',padding:16,borderRadius:17,marginBottom:10},primaryText:{textAlign:'center',color:'#fff',fontWeight:'900',fontSize:16},secondary:{backgroundColor:'#fff',padding:16,borderRadius:17,borderWidth:1,borderColor:'#DDE3EA',marginBottom:10},secondaryText:{textAlign:'center',fontWeight:'900',color:'#17233C'},dangerGhost:{padding:15,borderRadius:17,borderWidth:1,borderColor:'#E6B6B6',marginBottom:10},dangerText:{textAlign:'center',fontWeight:'900',color:'#B42318'},disabled:{opacity:.45}});
