import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useRouter } from "expo-router";
import { api, businessDate, getStoredProfile } from "../lib/backend";

type Hotel={location_id:string;display_name:string};
export default function HotelsScreen(){
 const router=useRouter(); const [hotels,setHotels]=useState<Hotel[]>([]),[selected,setSelected]=useState<Hotel|null>(null),[count,setCount]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{try{const p=await getStoredProfile();if(!p)return router.replace("/");const rows=await api<Hotel[]>("/rest/v1/hotel_activation_locations?select=location_id,display_name&active=eq.true&order=sort_order.asc");setHotels(rows??[])}catch(e){Alert.alert("تعذر تحميل الفنادق",e instanceof Error?e.message:"حاول مرة أخرى")}finally{setLoading(false)}})()},[router]);
 const save=async()=>{const qty=Number(count);if(!selected||!Number.isInteger(qty)||qty<=0)return Alert.alert("بيانات ناقصة","اختر الفندق وأدخل عدد التفعيلات");setSaving(true);try{const p=await getStoredProfile();if(!p)throw new Error("يجب تسجيل الدخول");await api("/rest/v1/hotel_activations",{method:"POST",body:JSON.stringify({employee_id:p.id,hotel_location_id:selected.location_id,business_date:businessDate(),activation_count:qty})},"resolution=merge-duplicates,return=minimal");Alert.alert("تم الحفظ","تم تسجيل تفعيلات الفندق بنجاح");setCount("");setSelected(null)}catch(e){Alert.alert("تعذر الحفظ",e instanceof Error?e.message:"حاول مرة أخرى")}finally{setSaving(false)}};
 return <SafeAreaView style={s.page}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>تفعيلات الفنادق</Text></View>{loading?<ActivityIndicator style={{marginTop:40}} color="#168CFF"/>:<ScrollView contentContainerStyle={s.content}><Text style={s.label}>اختر الفندق</Text>{hotels.map(h=><Pressable key={h.location_id} style={[s.hotel,selected?.location_id===h.location_id&&s.selected]} onPress={()=>setSelected(h)}><Text style={s.hotelText}>{h.display_name}</Text></Pressable>)}<Text style={s.label}>عدد التفعيلات</Text><TextInput value={count} onChangeText={setCount} keyboardType="number-pad" placeholder="0" placeholderTextColor="#718096" style={s.input}/><TouchableOpacity disabled={saving} onPress={save} style={s.save}><Text style={s.saveText}>{saving?"جاري الحفظ…":"حفظ التفعيلات"}</Text></TouchableOpacity></ScrollView>}</SafeAreaView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#061728"},header:{height:66,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:"#10314E"},back:{color:"#69B7FF",fontSize:38},title:{color:"#fff",fontSize:20,fontWeight:"900"},content:{padding:16,paddingBottom:40},label:{color:"#D8E7F5",fontWeight:"900",fontSize:16,textAlign:"right",marginVertical:12},hotel:{backgroundColor:"#0B2239",borderWidth:1,borderColor:"#15466E",borderRadius:14,padding:15,marginBottom:8},selected:{borderColor:"#168CFF",backgroundColor:"#0B3153"},hotelText:{color:"#fff",fontWeight:"800",textAlign:"right"},input:{backgroundColor:"#081B2D",borderWidth:1,borderColor:"#183E5D",borderRadius:15,padding:15,color:"#fff",textAlign:"right",fontSize:18},save:{backgroundColor:"#168CFF",borderRadius:16,padding:16,marginTop:18},saveText:{color:"#fff",fontWeight:"900",fontSize:17,textAlign:"center"}});