import { useEffect, useMemo, useState } from 'react';
import { Alert, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { currentProfile } from '@/lib/api';
import { supabase } from '@/lib/supabase';
import { Button, Pill, ScreenTitle } from '@/lib/ui';
import { C, R } from '@/lib/theme';

const ym=()=>{const d=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Riyadh'});return {year:+d.slice(0,4),month:+d.slice(5,7)}};
export default function Manage(){
 const router=useRouter();const [me,setMe]=useState<any>();const [rows,setRows]=useState<any[]>([]);const [query,setQuery]=useState('');const [refreshing,setRefreshing]=useState(false);const [busy,setBusy]=useState('');const [points,setPoints]=useState<Record<string,string>>({});
 async function load(){const p=await currentProfile();setMe(p);const {year,month}=ym();const [pr,db,ob]=await Promise.all([supabase.from('profiles').select('id,full_name,username,active,auth_user_id').eq('role','employee').order('full_name'),supabase.from('device_bindings').select('employee_id,active,migration_pending,device_label').eq('active',true),supabase.from('opening_balances').select('employee_id,points').eq('year',year).eq('month',month).eq('package_code','58')]);if(pr.error)throw pr.error;const out=(pr.data||[]).map(x=>({...x,device:(db.data||[]).find(d=>d.employee_id===x.id),opening:(ob.data||[]).find(o=>o.employee_id===x.id)?.points||0}));setRows(out);setPoints(Object.fromEntries(out.map(x=>[x.id,String(x.opening)])))}
 useEffect(()=>{load().catch(()=>{})},[]);
 const shown=useMemo(()=>rows.filter(r=>!query.trim()||String(r.full_name).includes(query.trim())||String(r.username||'').includes(query.trim())),[rows,query]);
 const canWrite=me?.role==='system_admin';
 async function act(id:string,fn:()=>Promise<any>,msg:string){setBusy(id);try{await fn();await load();Alert.alert('تم',msg)}catch(e:any){Alert.alert('تعذر التنفيذ',e.message||'حدث خطأ')}finally{setBusy('')}}
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.wrap} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false)}}/>}>
  <ScreenTitle eyebrow="الإعدادات الإدارية" title="إدارة الموظفين" right={<TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>رجوع</Text></TouchableOpacity>}/>
  <Text style={s.desc}>الحالة، ربط الجهاز والرصيد الافتتاحي. إيقاف الموظف يمنع صلاحياته التشغيلية فورًا.</Text>
  <TextInput style={s.search} value={query} onChangeText={setQuery} placeholder="ابحث عن موظف" placeholderTextColor={C.faint} textAlign="right"/>
  {shown.map(r=><View key={r.id} style={s.card}><View style={s.top}><View style={{flex:1}}><Text style={s.name}>{r.full_name}</Text><Text style={s.user}>{r.username}</Text></View><Pill text={r.active?'نشط':'موقوف'} tone={r.active?'success':'danger'}/></View>
    <View style={s.infoRow}><View style={s.info}><Text style={s.infoLabel}>الدخول الجديد</Text><Text style={s.infoValue}>{r.auth_user_id?'مربوط':'غير مفعّل'}</Text></View><View style={s.info}><Text style={s.infoLabel}>الجهاز</Text><Text style={s.infoValue}>{r.device?'مربوط':'غير مربوط'}</Text></View></View>
    {canWrite&&<><View style={s.balance}><View style={{flex:1}}><Text style={s.balanceLabel}>الرصيد الافتتاحي - نقاط</Text><TextInput value={points[r.id]??'0'} onChangeText={v=>setPoints(x=>({...x,[r.id]:v.replace(/[^0-9-]/g,'').slice(0,6)}))} keyboardType="numbers-and-punctuation" style={s.balanceInput} textAlign="center"/></View><TouchableOpacity style={s.saveSmall} disabled={busy===r.id} onPress={()=>{const {year,month}=ym();act(r.id,async()=>{const {error}=await supabase.rpc('admin_set_opening_points',{p_employee_id:r.id,p_year:year,p_month:month,p_points:parseInt(points[r.id]||'0',10)||0});if(error)throw error},'تم تحديث الرصيد الافتتاحي')}}><Text style={s.saveSmallText}>حفظ</Text></TouchableOpacity></View>
    <View style={s.actions}><View style={{flex:1}}><Button disabled={!!busy} variant={r.active?'danger':'primary'} title={r.active?'إيقاف الموظف':'تنشيط الموظف'} onPress={()=>Alert.alert(r.active?'إيقاف الموظف':'تنشيط الموظف',r.active?'سيتم منع حسابه من تنفيذ أي عملية.':'سيعود الحساب للعمل بعد التفعيل.',[{text:'إلغاء'},{text:'تأكيد',style:r.active?'destructive':'default',onPress:()=>act(r.id,async()=>{const {error}=await supabase.rpc('admin_set_employee_active',{p_employee_id:r.id,p_active:!r.active});if(error)throw error},r.active?'تم إيقاف الموظف':'تم تنشيط الموظف')}])}/></View><View style={{flex:1}}><Button disabled={!!busy||!r.device} variant="secondary" title="السماح بتغيير الجهاز" onPress={()=>Alert.alert('تغيير الجهاز','سيتم فك الجهاز الحالي، ويُربط الجهاز الجديد عند أول عملية موثقة.',[{text:'إلغاء'},{text:'فك الربط',onPress:()=>act(r.id,async()=>{const {error}=await supabase.rpc('admin_release_device',{p_employee_id:r.id});if(error)throw error},'تم السماح بتغيير الجهاز')}])}/></View></View></>}
  </View>)}
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},wrap:{padding:18,paddingBottom:50},back:{color:C.primary,fontWeight:'900',fontSize:12},desc:{textAlign:'right',color:C.muted,fontSize:11,lineHeight:18,marginTop:7,marginBottom:14},search:{backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:R.md,paddingHorizontal:14,paddingVertical:12,color:C.ink,fontSize:14,marginBottom:12},card:{backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:R.lg,padding:15,marginBottom:10},top:{flexDirection:'row-reverse',alignItems:'flex-start',gap:10},name:{textAlign:'right',fontSize:15,fontWeight:'900',color:C.ink},user:{textAlign:'right',fontSize:10,color:C.muted,marginTop:3},infoRow:{flexDirection:'row-reverse',gap:8,marginTop:12},info:{flex:1,backgroundColor:C.bg,borderRadius:R.sm,padding:10},infoLabel:{textAlign:'right',fontSize:9,color:C.faint},infoValue:{textAlign:'right',fontSize:12,fontWeight:'900',color:C.ink,marginTop:4},balance:{flexDirection:'row-reverse',alignItems:'flex-end',gap:8,marginTop:12},balanceLabel:{textAlign:'right',fontSize:10,color:C.muted,fontWeight:'700'},balanceInput:{backgroundColor:C.bg,borderWidth:1,borderColor:C.line,borderRadius:R.sm,padding:9,marginTop:5,fontWeight:'900',color:C.ink},saveSmall:{backgroundColor:C.primary,borderRadius:R.sm,paddingHorizontal:15,paddingVertical:11},saveSmallText:{color:'#fff',fontWeight:'900',fontSize:11},actions:{flexDirection:'row-reverse',gap:8,marginTop:12}});
