import { useEffect, useState } from 'react';
import { RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { currentProfile } from '@/lib/api';
import { C, R } from '@/lib/theme';
import { ScreenTitle } from '@/lib/ui';
export default function Notifications(){const router=useRouter();const [rows,setRows]=useState<any[]>([]);const [refreshing,setRefreshing]=useState(false);async function load(){const p=await currentProfile();const {data}=await supabase.from('notifications').select('*').eq('user_id',p.id).order('created_at',{ascending:false}).limit(80);setRows(data||[]);const unread=(data||[]).filter(x=>!x.read_at).map(x=>x.id);if(unread.length)await supabase.from('notifications').update({read_at:new Date().toISOString()}).in('id',unread)}useEffect(()=>{load().catch(()=>{})},[]);
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.wrap} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false)}}/>}><ScreenTitle eyebrow="المركز" title="الإشعارات" right={<TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>رجوع</Text></TouchableOpacity>}/><Text style={s.sub}>التنبيهات المتعلقة بالشفت والمبيعات والاعتمادات تظهر هنا.</Text>{rows.length?rows.map(x=><View style={s.card} key={x.id}><View style={s.dot}/><View style={{flex:1}}><Text style={s.ct}>{x.title}</Text><Text style={s.body}>{x.body}</Text><Text style={s.date}>{new Date(x.created_at).toLocaleString('ar-SA',{timeZone:'Asia/Riyadh'})}</Text></View></View>):<View style={s.emptyBox}><Text style={s.emptyIcon}>✓</Text><Text style={s.emptyTitle}>لا توجد إشعارات</Text><Text style={s.empty}>أي تنبيه جديد سيظهر هنا تلقائيًا.</Text></View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},wrap:{padding:18,paddingBottom:50},back:{color:C.primary,fontWeight:'900',fontSize:12},sub:{textAlign:'right',color:C.muted,fontSize:12,marginTop:7,marginBottom:18},card:{backgroundColor:C.card,borderRadius:R.lg,padding:15,marginBottom:10,borderWidth:1,borderColor:C.line,flexDirection:'row-reverse',gap:10},dot:{width:9,height:9,borderRadius:5,backgroundColor:C.primary,marginTop:5},ct:{textAlign:'right',fontWeight:'900',fontSize:14,color:C.ink},body:{textAlign:'right',marginTop:5,color:C.muted,lineHeight:19,fontSize:12},date:{textAlign:'right',marginTop:8,color:C.faint,fontSize:9},emptyBox:{alignItems:'center',backgroundColor:C.card,borderRadius:R.xl,borderWidth:1,borderColor:C.line,padding:30,marginTop:16},emptyIcon:{fontSize:24,color:C.primary,fontWeight:'900'},emptyTitle:{fontSize:16,fontWeight:'900',color:C.ink,marginTop:8},empty:{color:C.muted,fontSize:11,marginTop:5}});
