import { useEffect, useMemo, useState } from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { currentProfile, submitSales } from '@/lib/api';
import { supabase } from '@/lib/supabase';
import { Button, Pill, ScreenTitle } from '@/lib/ui';
import { C, R } from '@/lib/theme';

const P:any={p35:{code:'35',pts:5},p58:{code:'58',pts:10},p75:{code:'75',pts:10},p104:{code:'104',pts:12}};
const businessDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()-2*60*60*1000));
export default function Sales(){const router=useRouter();const [vals,setVals]=useState<any>({p35:'0',p58:'0',p75:'0',p104:'0'});const [status,setStatus]=useState('');const [revision,setRevision]=useState(0);const [busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{const p=await currentProfile();const {data}=await supabase.from('daily_operations').select('package_35,package_58,package_75,package_104,sales_status,revision_count,shift_status').eq('employee_id',p.id).eq('work_date',businessDate()).maybeSingle();if(!data||data.shift_status!=='ended')return;setVals({p35:String(data.package_35||0),p58:String(data.package_58||0),p75:String(data.package_75||0),p104:String(data.package_104||0)});setStatus(data.sales_status||'');setRevision(data.revision_count||0)})()},[]);
 const locked=status==='approved'||status==='submitted'||(status==='rejected'&&revision>=1);const nums=useMemo(()=>Object.fromEntries(Object.keys(P).map(k=>[k,Math.max(0,parseInt(vals[k]||'0',10)||0)])),[vals]);const units=Object.values(nums).reduce((a:any,b:any)=>a+b,0) as number;const points=Object.keys(P).reduce((a,k)=>a+nums[k]*P[k].pts,0);
 async function send(){setBusy(true);try{await submitSales(nums.p35,nums.p58,nums.p75,nums.p104);Alert.alert('تم الإرسال','تم إرسال مبيعات اليوم للاعتماد');router.back()}catch(e:any){Alert.alert('تعذر الإرسال',e.message||'حدث خطأ')}finally{setBusy(false)}}
 const tone=status==='approved'?'success':status==='rejected'?'danger':status==='submitted'?'warning':'neutral';const label=status==='approved'?'معتمد':status==='rejected'?'مرفوض':status==='submitted'?'بانتظار الاعتماد':'مسودة';
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.wrap} keyboardShouldPersistTaps="handled"><ScreenTitle eyebrow="اليوم" title="تسجيل المبيعات" right={<TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>رجوع</Text></TouchableOpacity>}/><View style={s.summary}><View><Text style={s.sumLabel}>إجمالي الشرائح</Text><Text style={s.sumValue}>{units}</Text></View><View><Text style={s.sumLabel}>نقاط اليوم</Text><Text style={s.sumValue}>{points}</Text></View><Pill text={label} tone={tone as any}/></View><View style={s.card}>{Object.keys(P).map(k=><View key={k} style={s.saleRow}><View style={s.pkgInfo}><View style={s.pkgBadge}><Text style={s.pkgCode}>{P[k].code}</Text></View><View><Text style={s.pkgTitle}>باقة {P[k].code}</Text><Text style={s.pkgHint}>{P[k].pts} نقاط لكل شريحة</Text></View></View><View style={s.qtyBox}><TouchableOpacity disabled={locked} onPress={()=>setVals((x:any)=>({...x,[k]:String(Math.max(0,(parseInt(x[k])||0)-1))}))}><Text style={s.step}>−</Text></TouchableOpacity><TextInput keyboardType="number-pad" editable={!locked} value={vals[k]} onChangeText={v=>setVals((x:any)=>({...x,[k]:v.replace(/[^0-9]/g,'').slice(0,3)}))} style={s.qty} textAlign="center"/><TouchableOpacity disabled={locked} onPress={()=>setVals((x:any)=>({...x,[k]:String(Math.min(999,(parseInt(x[k])||0)+1))}))}><Text style={s.step}>+</Text></TouchableOpacity></View></View>)}{status==='rejected'&&<View style={s.rejectNote}><Text style={s.rejectText}>{revision<1?'لديك تعديل واحد متاح. بعد الإرسال الثاني لن يمكن التعديل مرة أخرى.':'تم استخدام فرصة التعديل الوحيدة.'}</Text></View>}<Button disabled={locked||busy} title={locked?(status==='approved'?'تم اعتماد المبيعات':'المبيعات قيد الاعتماد'):'حفظ وإرسال للاعتماد'} onPress={send}/></View></ScrollView></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},wrap:{padding:18,paddingBottom:50},back:{color:C.primary,fontWeight:'900',fontSize:12},summary:{backgroundColor:C.navy,borderRadius:R.xl,padding:18,marginTop:20,flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',gap:12},sumLabel:{textAlign:'right',color:'#AEBAC8',fontSize:10},sumValue:{textAlign:'right',color:'#fff',fontSize:27,fontWeight:'900',marginTop:3},card:{backgroundColor:C.card,borderRadius:R.xl,borderWidth:1,borderColor:C.line,padding:16,marginTop:16},saleRow:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center',paddingVertical:13,borderBottomWidth:1,borderBottomColor:C.line},pkgInfo:{flexDirection:'row-reverse',alignItems:'center',gap:10},pkgBadge:{width:44,height:44,borderRadius:14,backgroundColor:C.primarySoft,alignItems:'center',justifyContent:'center'},pkgCode:{fontWeight:'900',fontSize:15,color:C.primary},pkgTitle:{textAlign:'right',fontWeight:'900',color:C.ink,fontSize:14},pkgHint:{textAlign:'right',color:C.faint,fontSize:9,marginTop:3},qtyBox:{flexDirection:'row',alignItems:'center',backgroundColor:C.bg,borderRadius:14,paddingHorizontal:8},step:{fontSize:24,fontWeight:'700',color:C.primary,paddingHorizontal:7,paddingVertical:5},qty:{width:48,fontSize:18,fontWeight:'900',color:C.ink,paddingVertical:7},rejectNote:{backgroundColor:C.dangerSoft,borderRadius:R.sm,padding:11,marginVertical:14},rejectText:{textAlign:'right',color:C.danger,fontSize:11,fontWeight:'700',lineHeight:18}});
