import { useEffect, useState } from 'react';
import { Alert, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { currentProfile, submitSales } from '@/lib/api';
import { supabase } from '@/lib/supabase';

export default function Sales(){const router=useRouter();const [vals,setVals]=useState({p35:'0',p58:'0',p75:'0',p104:'0'});const [status,setStatus]=useState('');const [revision,setRevision]=useState(0);const [busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{const p=await currentProfile();const d=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const {data}=await supabase.from('daily_operations').select('package_35,package_58,package_75,package_104,sales_status,revision_count').eq('employee_id',p.id).eq('work_date',d).maybeSingle();if(data){setVals({p35:String(data.package_35||0),p58:String(data.package_58||0),p75:String(data.package_75||0),p104:String(data.package_104||0)});setStatus(data.sales_status||'');setRevision(data.revision_count||0)}})()},[]);
 const locked=status==='approved'||status==='submitted'||(status==='rejected'&&revision>=1);
 async function send(){setBusy(true);try{const n=(k:keyof typeof vals)=>Math.max(0,parseInt(vals[k]||'0',10)||0);await submitSales(n('p35'),n('p58'),n('p75'),n('p104'));Alert.alert('تم','تم إرسال المبيعات للاعتماد');router.back()}catch(e:any){Alert.alert('تعذر الإرسال',e.message||'حدث خطأ')}finally{setBusy(false)}}
 return <SafeAreaView style={s.page}><View style={s.wrap}><View style={s.head}><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>رجوع</Text></TouchableOpacity><Text style={s.title}>مبيعات اليوم</Text></View><Text style={s.note}>النقاط: 35 = 5 • 58 = 10 • 75 = 10 • 104 = 12</Text>
 <View style={s.card}>{(['p35','p58','p75','p104'] as const).map(k=><View key={k}><Text style={s.label}>باقة {k.slice(1)}</Text><TextInput keyboardType="number-pad" editable={!locked} value={vals[k]} onChangeText={v=>setVals(x=>({...x,[k]:v}))} style={[s.input,locked&&s.lock]} textAlign="center"/></View>)}
 {!!status&&<Text style={s.state}>الحالة: {status==='approved'?'معتمد':status==='submitted'?'بانتظار الاعتماد':status==='rejected'?'مرفوض':'مسودة'} {status==='rejected'?`• التعديل ${revision}/1`:''}</Text>}
 <TouchableOpacity disabled={locked||busy} style={[s.btn,(locked||busy)&&{opacity:.45}]} onPress={send}><Text style={s.btnText}>{locked?'لا يمكن التعديل الآن':'حفظ وإرسال للاعتماد'}</Text></TouchableOpacity></View></View></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F4F7FB'},wrap:{padding:20},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:15},title:{fontSize:24,fontWeight:'900',color:'#17233C'},back:{color:'#159A74',fontWeight:'800'},note:{textAlign:'right',color:'#707C8C',marginBottom:15},card:{backgroundColor:'#fff',borderRadius:24,padding:20},label:{textAlign:'right',fontWeight:'900',color:'#17233C',marginBottom:7},input:{backgroundColor:'#F4F7FA',borderRadius:14,padding:14,fontSize:20,fontWeight:'800',marginBottom:14},lock:{opacity:.6},state:{textAlign:'right',marginVertical:10,fontWeight:'800',color:'#6A7480'},btn:{backgroundColor:'#159A74',padding:16,borderRadius:16,marginTop:8},btnText:{textAlign:'center',color:'#fff',fontWeight:'900'}});
